ci:
  autofix_commit_msg: "style(pre-commit.ci): auto fixes from pre-commit hooks"
  autoupdate_commit_msg: "style(pre-commit.ci): pre-commit autoupdate"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        additional_dependencies: [prettier, prettier-plugin-toml, prettier-plugin-ini]
        types: ["ini", "toml", "yaml"]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16 # Use the ref you want to point at
    hooks:
      - id: mdformat
        # Optionally add plugins
        additional_dependencies:
          - mdformat-gfm
          - mdformat-black

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.18.4
    hooks:
      - id: check-github-workflows
