name: {{ cookiecutter.repo_name }}
channels:
    - conda-forge
dependencies:
    - python=3.11
    - gdal=3.6.3
    - myst-parser=1.0.0
    - sphinx=6.1.3
    - pip=23.0.1
    - pip:
      - pydata-sphinx-theme==0.13.3
